[package]
name = "font-icons-scraper"
version = "0.1.0"
edition = "2021"
about = "A tool to extract SVG icons from font files used by popular icon font services."
author = "Dilshad <dilshadplayingminecraft@outlook.com>"

[dependencies]
base64 = "0.13"
clap = { version = "4.3.8", features = ["derive"] }
futures = "0.3.28"
lazy_static = "1.4.0"
regex = "1.8.4"
reqwest = "0.11.18"
tokio = { version = "1.28.2", features = ["rt", "macros", "rt-multi-thread"] }
ttf-parser = "0.19.1"
url = "2.4.0"
xml-rs = "0.8.14"
xmlwriter = "0.1.0"
