[package]
name = "font-icons-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
lazy_static = "1.4.0"
regex = "1.8.4"
reqwest = "0.11.18"
tokio = { version = "1.28.2", features = ["rt", "macros", "rt-multi-thread"] }
ttf-parser = "0.19.1"
url = "2.4.0"
xml-rs = "0.8.14"
xmlwriter = "0.1.0"
