[package]
name = "font-icons-scraper"
version = "0.1.0"
edition = "2021"
about = "A tool to extract SVG icons from font files used by popular icon font services."
author = "Dilshad <dilshadplayingminecraft@outlook.com>"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
futures = "0.3.30"
lazy_static = "1.4.0"
regex = "1.10.2"
reqwest = "0.11.23"
tokio = { version = "1.35.1", features = ["full"] }
ttf-parser = "0.20.0"
url = "2.5.0"
