name: Compile and Save artifact

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Cache Rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: linux-cargo-build

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
          default: true

      - name: Install musl
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools
          version: 1.0

      - name: Compile
        run: |
          cargo b -r --target x86_64-unknown-linux-musl
          mkdir builds
          
          cp target/x86_64-unknown-linux-musl/release/font-icons-scraper builds/font-icons-scraper

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          path: builds
