name: Compile

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Compile
        run: |
          cargo build --release
          mkdir artifacts

          cp target/release/font-icons-scraper artifacts/font-icons-scraper
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifacts
